### ISSUE TITLE
Очень проблемно скачать клиент

### ISSUE THREAD

**Issue by simon-kloyns** [Exaktus/mRemoteNC#14]
Доброго времени суток !  Клиент по пимпе download  на сайте http://exaktus.github.io/mRemoteNC/ не качается - качается окольными путями через cnet.

**Comment by pyhedgehog** [comment]
В [github release](https://github.com/Exaktus/mRemoteNC/releases) есть ссылка на архив. Мне кажется будет правильнее переформулировать проблему по английски (#16) и закрыть этот дефект.

**Comment by Exaktus** [comment]
Исправил.
